import { KEEPA_RATE_LIMIT } from "../constants";
import { KeepaLimits } from "../types/KeepaResponse";

/*
  Example:
   "timestamp": 1739780860475,
  "tokensLeft": 3596,
  "refillIn": 18456,
  "refillRate": 60,
  "tokenFlowReduction": 0.0,
  "tokensConsumed": 3,

*/

export class KeepaRatelimit {
  // Number of tokens generated by your active subscriptions.
  refillRate: number = KEEPA_RATE_LIMIT;
  // Time in milliseconds until your token bucket will be refilled (happens every minute).
  refillIn: number = 0;
  // The time in milliseconds between each token refill.
  tokensLeft: number = Infinity;
  // The number of tokens consumed by this request.
  tokensConsumed: number = 0;
  // Tracking products through the API reduces your actual token refill rate by this value (rounded to an integer).
  tokenFlowReduction: number = 0;

  constructor() {}

  setCurrentLimits(args: KeepaLimits) {
    this.refillIn = args.refillIn;
    this.tokenFlowReduction = args.tokenFlowReduction;
    this.tokensLeft = args.tokensLeft;
  }
}
